name: NanoServer MSVC

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-nanoserver-msvc-winsdk-x64-build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Restore Image Cache
        uses: actions/cache/restore@v4
        id: restore-buildkit
        with:
          path: |
            buildkit
            
          key: buildkit-${{ runner.os }}-
          restore-keys: |
            buildkit-${{ runner.os }}-

      - name: Setup Buildkit
        shell: pwsh
        run: |
            # Create required directories
            New-Item -ItemType Directory -Path "buildkit/logs" -Force

            Invoke-WebRequest -Uri "https://github.com/moby/buildkit/releases/download/v0.20.1/buildkit-v0.20.1.windows-amd64.tar.gz" -OutFile "buildkit.tar.gz"
            tar -xf buildkit.tar.gz -C buildkit
            
            Invoke-WebRequest -Uri "https://github.com/containerd/containerd/releases/download/v2.0.4/containerd-2.0.4-windows-amd64.tar.gz" -OutFile "containerd.tar.gz"
            tar -xf containerd.tar.gz -C buildkit

            $Bin = "${{ github.workspace }}\buildkit\bin"
            $CurrentPath = [System.Environment]::GetEnvironmentVariable("Path", "Machine")
            [System.Environment]::SetEnvironmentVariable("Path", "$CurrentPath;$Bin", "Machine")
            $env:Path += ";$Bin"
            
      - uses: fawazahmed0/action-debug-vscode@main

      - name: TEST
        shell: pwsh
        run: |    
            Start-Process containerd.exe `
              -RedirectStandardOutput "buildkit/logs/containerd.log" `
              -RedirectStandardError "buildkit/logs/containerd_error.log" `
              -NoNewWindow -PassThru

            $timeout = [datetime]::Now.AddSeconds(5)
            while (-not (Test-NetConnection -ComputerName "localhost" -Port 2375 -InformationLevel Quiet)) {
                if ([datetime]::Now -gt $timeout) { Write-Error "Timeout waiting for containerd to start"; exit 1 }
                Start-Sleep -Seconds 1
            }
            
            .\cni\setup-nat.ps1

            Start-Process buildkitd.exe `
              -ArgumentList @("--containerd-cni-config-path=${{ github.workspace }}\buildkit\containerd\cni\conf\0-containerd-nat.conf",
                              "--containerd-cni-binary-dir=${{ github.workspace }}\buildkit\containerd\cni\bin") `
              -RedirectStandardOutput "buildkit/logs/buildkitd.log" `
              -RedirectStandardError "buildkit/logs/buildkitd_error.log" `
              -NoNewWindow -PassThru
            
      - name: Save Image Cache
        id: cache-buildkit
        uses: actions/cache/save@v4
        with:
          path: |
            buildkit
          key: buildkit-${{ runner.os }}-
