name: NanoServer MSVC

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-nanoserver-msvc-winsdk-x64-build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Restore Cached WSL Kernel & VHDX
        uses: actions/cache@v4
        id: wsl_cache
        with:
          path: |
            linux/bzImage
            linux/ext4.vhdx
            linux/wsl.msi
          key: wsl-files-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            wsl-files-${{ runner.os }}-

      - name: Configure WSL
        shell: pwsh
        run: |
          wsl/setup-wsl.ps1 -WorkspaceDir "${{ github.workspace }}"

      - name: Save WSL Kernel & VHDX to Cache
        uses: actions/cache@v4
        with:
          path: |
            linux/bzImage
            linux/ext4.vhdx
            linux/wsl.msi
          key: wsl-files-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            wsl-files-${{ runner.os }}-

      - uses: fawazahmed0/action-debug-vscode@main
