name: NanoServer MSVC

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-nanoserver-msvc-winsdk-x64-build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download BuildKit
        run: |
          curl -SL --output buildx.exe https://github.com/docker/buildx/releases/download/v0.22.0-rc1/buildx-v0.22.0-rc1.windows-amd64.exe

      - name: Build Image
        shell: pwsh
        run: |
          docker build -f docker/mount.dockerfile -t app:latest .

      - name: Cache Image with GHA
        shell: pwsh
        run: |
          $env:DOCKER_BUILDKIT=1
          $env:BUILDX_EXPERIMENTAL=1
          .\buildx.exe build --push -f docker/xcache.dockerfile --cache-to type=gha,mode=max --cache-from type=gha -t app:latest .
