name: NanoServer MSVC

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-nanoserver-msvc-winsdk-x64-build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Restore Cached Image TAR
        uses: actions/cache@v4
        with:
          path: cache-image.tar
          key: docker-image-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            docker-image-${{ runner.os }}-

      - name: Load Cached Image
        shell: pwsh
        id: load_cache
        run: |
          if (Test-Path cache-image.tar) {
            docker load -i cache-image.tar
            echo "CACHE_HIT=true" >> $env:GITHUB_ENV
          }

      - name: Build Image Without Cache
        if: env.CACHE_HIT != 'true'
        shell: pwsh
        run: |
          docker build -f docker/mount.dockerfile -t app:latest .

      - name: Build Image With Cache
        if: env.CACHE_HIT == 'true'
        shell: pwsh
        run: |
          docker build --cache-from app:latest -f docker/mount.dockerfile -t app:latest .

      - name: Save Docker Image to TAR
        shell: pwsh
        run: |
          docker save -o cache-image.tar app:latest

      - name: Cache Image TAR
        uses: actions/cache@v4
        with:
          path: cache-image.tar
          key: docker-image-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            docker-image-${{ runner.os }}-
